name: Download and Commit Files

on:
  workflow_dispatch:
  schedule:  # Run daily
    - cron:  '0 0 * * *'  

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Download Files from List
        run: ./download_files.sh urls.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
