name: Download and Commit Files

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'  

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Files from List
        run: ./download_files.sh urls.txt

      - name: Commit Changes (if any)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add downloads 
          git commit -m "Automated daily updates"
          git push 
