name: Download and Commit Files

on:
  schedule:  # Run daily
    - cron:  '0 5 * * *'  

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Files from List
        run: ./download_files.sh urls.txt  # Assuming script is named download_files.sh

      - name: Check for Changes
        id: check_changes
        run: |
          if [ -d downloads ] && [ "$(ls -A downloads)" ] && ! git diff --quiet; then 
            echo "::set-output name=changes_detected::true"
          fi

      - name: Commit Changes (if any)
        if: ${{ steps.check_changes.outputs.changes_detected == 'true' }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add downloads 
          git commit -m "Automated daily updates"
          git push 